resolver: lts-13.5
save-hackage-creds: false

flags:
  hakyll:
    previewServer: true
    watchServer:   true
    checkExternal: true
    usePandoc:     true
    buildWebsite:  true

packages:
  - '.'

nix:
  enable: false
  packages:
    - zlib

build:
  haddock: true
  haddock-hyperlink-source: true
  haddock-deps: false

extra-deps:
- 'lrucache-1.2.0.1'
- 'pandoc-2.6'
- 'pandoc-citeproc-0.16'
- 'ipynb-0.1'
